language: node_js
node_js:
  - '8'
  - '6'

cache:
  yarn: true

script:
  - yarn run lint
  - yarn test

deploy:
  - provider: script
    script: tools/publish.sh
    skip_cleanup: true
    on:
      tags: true
